name: Organization CI

on:
    push:
        branches: [ $default-branch ]
    pull_reequests:
        branches: [ $default-branch ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v4

      - name: Run a one-line script
        run: |
          echo "We meet again mr Bond"


